# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20171117_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='desc',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
