# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_role_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('contact_no', models.IntegerField(max_length=10)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
