# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_personalinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='second_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
