# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0009_auto_20171117_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True)),
                ('attendance', models.CharField(choices=[(b'PRESENT', b'Present'), (b'ABSENT', b'Absent'), (b'LATE', b'Late')], default=None, max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=32)),
                ('no_of_mentors', models.IntegerField()),
                ('no_of_student', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_students', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='first_name',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='second_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='second_name',
            new_name='school',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='contact_info',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(choices=[(b'MALE', b'Male'), (b'FEMALE', b'Female'), (b'OTHER', b'Other')], default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='contact_no',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.Employee'),
            preserve_default=False,
        ),
    ]
