# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20171118_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='contact_info',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_no',
            field=models.IntegerField(blank=True),
        ),
    ]
