# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20171118_0350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalInfo',
            new_name='OtherInfo',
        ),
    ]
